### ISSUE TITLE
Grand package system overhaul

### ISSUE THREAD

**Issue by fmease** [fmease/lushui#123]
Meta: Task: Write description. Note: We want to partially copy Cabal's package system (however with explicit _components_ (formerly known as crates or capsules) instead of a list of exposed modules). That is move away from Rust's package system: No "dev-dependencies" for example but component-specific dependencies. Also: Not just one library per package but several (with a "default" one) (see Cabal's sublibrary system, also [this blog](https://fgaz.me/posts/2019-11-14-cabal-multiple-libraries/) (a bit barren on the motivation though)).

The part of the package manifest describing components should be changed to look sth. like this:

```yaml
components: [
    {
        type: "library",
        name: "hello",
        dependencies: {
            core: {},
        },
    },
    {
        type: "executable",
        name: "example",
        # dependencies: { "hello": {} } # this is implicit right now but once we allow multiple libraries per package,
        # this becomes problematic as it is not as flexible
        dependencies: {
            core: {},
        }
    }
],
```

Or with a "common" definition (terminology will probably change, this is straight up taken from Cabal):

```yaml
components: [
    {
        use: "default",
        type: "library",
        name: "hello",
    },
    {
        use: "default",
        type: "executable",
        name: "example",
    }
],
commons: [
    {
        name: "default",
        dependencies: {
            core: {},
        }
    }
]
```

For the record, the equivalent to the above in the current version looks like this (although some stuff below could've been omitted for brevity):

```yaml
library: { name: "hello" },
executables: [{ name: "example" }],
dependencies: {
    core: {},
},
```
